# Site settings
title: Subsoil
email: subsoil4u@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal adventures under ground
baseurl: "/subsoil" # the subpath of your site, e.g. /blog/
url: "http://fannes.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  gfannes

# Build settings
markdown: kramdown
